name: Weekly Git Repo Backup

on:
  schedule:
    - cron: '0 3 * * 1'  # 매주 월요일 오전 3시 UTC (한국 기준 오후 12시)
  workflow_dispatch:      # 수동 실행도 가능하게

jobs:
  zip-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # .git 폴더까지 포함하려면 전체 히스토리가 필요

    - name: Zip repository including .git
      run: |
        cd ..
        zip -r repo-with-git.zip $GITHUB_REPOSITORY

    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: git-backup-$(date +%Y%m%d)
        name: Weekly Backup - $(date +%Y-%m-%d)
        files: ../repo-with-git.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
